version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: paintdb
      POSTGRES_USER: paintuser
      POSTGRES_PASSWORD: paintpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
